linters:
  auto-fix: false
  enable:
    - errcheck
    - goimports
    - revive
    - misspell
    - unconvert
    - unparam
    - nakedret
    - dupl
    - goconst
    - lll
run:
linters-settings:
  errcheck:
    check-type-assertions: true
  lll:
    line-length: 250
  dupl:
    threshold: 400
